### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by BillyMassey** [syliesox/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by syliesox** [comment]
Thanks for the feedback, Billy!
I have looked into the meta tag for mobile, I added it to my code, however, I don't see any difference between this and the original site. 
I have updated my code on github, Can you take a look and let me know if I'm using the meta tag incorrectly. From what I found on the internet, this is what my code is supposed to look like.

Also, quick question: when we talk about "responsiveness," does that mean that the quote's font should shrink as well when the screen gets smaller? I'm just trying to figure out exactly what is expected when we are working with a smaller screen. When I shrink my screen, the quote's font does not get smaller.

I appreciate it! Thanks! :-)

**Comment by BillyMassey** [comment]
Hi Julia -

It looks like you haven’t deployed the changes to heroku so you can’t test it out.  If you add this to your app,

<meta name="viewport" content="width=device-width, initial-scale=1">

Commit and push to heroku it should to the trick.

Hope this helps!

Cheers,
Billy

**Comment by syliesox** [comment]
Oh wow, that was an easy fix. I didn't think to deploy it to heroku
previously, so thanks. I think it's all set, but if not, definitely let me
know.

Thanks for the help! :-)
